trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.18.0'
            displayName: Install NodeJS
          - script: |
              npm install
            displayName: 'npm install'
          - script: |
              npm run build
            displayName: 'build'
          - task: CopyFiles@2
            inputs:
              Contents: |
                .next/**
                package.json
                node_modules/**
                public/**
                ecosystem.config.js
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'nextJS-ssr-demo-artifact'
              artifactType: 'pipeline' # artifact publish location
  - stage: Deploy (CD)
    jobs:
      - deployment:
        environment: Prod
        strategy:
          runOnce:
            deploy: 
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: Downloading artifact
                  inputs:
                    buildType: 'current'
                    artifactName: 'nextJS-ssr-demo-artifact'
                    targetPath: '$(System.ArtifactsDirectory)/nextJS-ssr-demo-artifact'
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: '<redacted>' # this is a service connection
                    appType: 'webAppLinux'
                    appName: 'free-next-learn-assess-app' # name of the app service we're deploying to
                    package: '$(System.ArtifactsDirectory)/nextJS-ssr-demo-artifact'
                    startUpCommand: 'pm2 --no-daemon start /home/site/wwwroot/ecosystem.config.js'